### PR TITLE
Chrome design

### PR DESCRIPTION
**Pull request by shinandruth**
* Sign in/ Sign up button is designed and redirects to respective web pages
* frontend html/css start implemented 

* Note: had to delete db and _python manage.py migrate_ again for db connect issues. You might need to _python manage.py migrate_  as well.
* There are a couple repeated commits due to updating with master before PR. but everything is correct as is.

### CODE REVIEW

**Comment by jhbaang** [comment]
Good. I will try to link chrome extension and backend (django).

**Comment by shinandruth** [comment]
wait can you hold off for a second, let me fix the check real quick.

**Comment by jhbaang** [comment]
sure. please let me know whey you are fixed completely.

**Comment by jhbaang** [comment]
design improvement is awesome!
I like stars and login/signout button effect.
However, rating part is little bit strange.
screenshot 2017-12-02 21 22 38

**Comment by shinandruth** [comment]
@jhbaang thanks for the feedback! As I said in the kakao group chat, I only designed the signin/signout and the star implements for now. The rating portion will need to change after we convert from textbox to star. It didn't make sense for me to design that when it was not going to be in the final design.

**Comment by jhbaang** [comment]
@shinandruth 
Okay! Actually, I can fix it. I will add some commits about above problems.
I will add commits for connecting to django backend as well.

**Comment by jhbaang** [comment]
@shinandruth 
I am now trying to send rating info(adfree score with star rating) to django backend. Could you give me some reference sites which you saw for implementing `star rating html`?

**Comment by shinandruth** [comment]
@jhbaang If you don't mind, I would like to implement the design for the chrome extension. I hope that is okay with you. Regarding your change request, those three files are not in the commits. They will not be added to the master for this PR. As you can see, that file was deleted, not added. This was due to the db issue I discussed in the comments. For the HTML star implementation: https://www.cssscript.com/demo/accessible-star-rating-system-pure-css/

**Comment by jhbaang** [comment]
@shinandruth 
I found that the loading speed of chrome extension has become very slow. I anticipate the reason of that is using bootstrap css and js from link(`http://maxcdn.bootstrapcdn.com`).
Is there no way to use css file with our file, not link?

**Comment by jhbaang** [comment]
@shinandruth 
Sorry... I mistook.

**Comment by shinandruth** [comment]
@jhbaang  no worries, it happens. As for your feedback, I see your concern there and you're right, for my local, it takes about 3 seconds for it to load, definitely not ideal. After investigating, I checked the _api-team_ branch and the chrome extension load time is about 3 seconds as well and that branch does not have any edits from this PR. I'm not so sure that the edits in this PR had an effect on the increase in chrome extension load time. Do you mind checking on your local?

**Comment by jhbaang** [comment]
perfect!

**Pull request merged**
