### PR TITLE
Post Score calculation

### PR DESCRIPTION
**Pull request by jhbaang**
## Summary
- Update score of Post when new rating is created.
- Show recently added fields of Post in Admin page.
- rename url_utils.py to utils.py for using this file more generally

## Details
- Score updating logic
> - (new adfree_score) = ((old adfree_score) * (old rating_count) + (rating adfree_score)) / (old rating_count + 1)
> - (new content_score) = ((old content_score) * (old rating_count) + (rating content_score)) / (old rating_count + 1)
> - (new rating_count) = (old rating_count + 1)
> - (new total_score) = (new adfree_score) * (0.5) + (new content_score) * (0.5)

### CODE REVIEW

**Comment by jhbaang** [comment]
@SoheeLee 
I implemented your requirement. Now score of post is updated whenever new rating is created. Please review this PR. Thanks.

**Comment by jhbaang** [comment]
@shinandruth did you pull this PR? `adfreereview_post.adfree_score` is implemented by @SoheeLee for `api-team` branch. This branch is created from `api-team` branch. Please check whether you pulled this PR appropriately or not.

**Comment by jhbaang** [comment]
@shinandruth  Please check `class Post` in check `backend/adfreereview/models.py` contains `adfree_score`, `content_score`, `total_score` for fields. These should be contained.

**Comment by shinandruth** [comment]
@jhbaang Thanks for your comment. If you check the _Edit_ of my comment, that issue has been solved via @SoheeLee 's suggestion.  in  `class Post ` all three fields are contained. The issue "no such table: django_session" is still present, however.

**Comment by jhbaang** [comment]
@shinandruth 
I think this error occurs because of removed db.sqlite3. Try command `python manage.py makemigrations` and `python manage.py migrate`?

**Comment by shinandruth** [comment]
@jhbaang turns out there was some issue with the db. Regardless, the issue can be fixed by deleting the db and rebooting it via _python manage.py mirgrate_. This works    
 
Another note: There's an issue with the type of input in chrome ext. I pus _1_, _1_, _test1_ and throws and input not valid error. Could you please check into this? Also, frontend->backend data isn't going through. but don't worry about this too much. I think this has to change because of the design of chrome anyways.

**Comment by jhbaang** [comment]
@shinandruth 
That is little bit awkward..... To me, the case you mentioned is not a problem. It works well.
When you see the problem which `frontend-->backend data is not going through`, please restart your django session and try it again please.

**Comment by shinandruth** [comment]
@jhbaang I don't think I conveyed myself accurately, what I mean by frontend->backend is when I input my rating into chrome extension, it doesn't go into the django db. Also, keep in mind that different machines will react differently. I know @SoheeLee was also having the same problem. Secondly, I'm not sure why _1,1,test1_ threw an error. Let's check this test case on the other two teammate's locals and see the results. @SoheeLee @quakkk Could you help us out on this one please? Thank you in advance! :)

**Comment by jhbaang** [comment]
Good!
@shinandruth 
I mean, if your machine works well but occasionally have some troubles in some cases, for that case, restart django session can be a naive solution.

**Comment by shinandruth** [comment]
@jhbaang thanks for your feedback, unfortunately, that doesn't seem to work for my case :(. regardless, that's okay because that will change once we change from textbox to star implementation. On another note, I would be happy to approve this PR once the branch conflict is resolved!

**Comment by jhbaang** [comment]
Okay, then can you merge this branch?

**Comment by shinandruth** [comment]
@jhbaang Would it be okay if we had the other two team members check the test case that throws an error on mine but not yours first?

**Comment by shinandruth** [comment]
everything looks good! merging.

**Pull request merged**
