### PR TITLE
Chromeext popupscore - showing score of post (adfreescore, contentscore)

### PR DESCRIPTION
**Pull request by jhbaang**
## Showing Scores [Adfree Score and Content Score]
I implemented some codes for showing `adfreescore` and `contentscore` of post.
When you clicked the chrome extension icon on specific blog post, you can easily see the adfreescore and contentscore of that post. all scores are calculated with mean. 

Please check below screen shots to understand
[showing score](https://www.dropbox.com/s/34jqqw7dtq4bihc/Screenshot%202017-11-25%2011.59.27.png?)

## Alert when the post is not evaluated yet.
When the post is not evaluated yet, chrome extension alert with special text `No one evaluate this post yet. Please be the first one!`

Please check below screen shots to understand
[alert message](https://www.dropbox.com/s/fhskow45nxvw5lq/Screenshot%202017-11-25%2011.59.11.png?)

### CODE REVIEW

**Comment by jhbaang** [comment]
Please check my commits works well on your environment. @SoheeLee @shinandruth @quakkk

**Comment by jhbaang** [comment]
Please do not merge this PR until all of the members can run this code on their own environment @shinandruth @SoheeLee @quakkk

**Comment by shinandruth** [comment]
works well on mine! Some suggestions for minor fixes
* if there are no ratings, the pop up appears on top right hand corner cut off. Let's move this so its not cut off
* remove rating output if there is not rating

@SoheeLee @quakkk please take priority to look at this PR first. I would like to use this verison to start designing. Thank you! :)

**Comment by jhbaang** [comment]
@shinandruth 
Thank you for reviewing. I will consider your review in next PR.

**Pull request merged**
